name: action-slack
description: Template repository for TypeScript Github Actions.
author: "@bluenovaio"
inputs:
  username:
    description: fo
    required: false
  channel:
    description: fo
    required: true
  text:
    description: fo
    required: true
  icon_emoji:
    description: foo
    required: false
  icon_url:
    description: foo
    required: false
runs:
  using: node12
  main: dist/index.js
