name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lintAndTest:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - id: runAction
        name: Run Action Code
        uses: ./
        with:
          webhook_url: https://hooks.slack.com/services/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
          text: Example Slack Message
          channel: "#oss-github-action"
